name: Publish to PyPI
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write    # Required for OIDC identity verification
      contents: write    # Required for creating releases and committing code
    steps:
      - uses: actions/checkout@v4

      - name: Run PyPi Publish
        uses: MineFartS/PyPi-Increment-Publish@v2
